version: 2
jobs:
  build:
    docker:
      - image: circleci/node:latest

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run: npm install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - run:
          command: npm run send-coverage
          environment:
            JEST_JUNIT_OUTPUT: 'reports/junit/js-test-results.xml'

      - run: npm run docs

      - run: npx semantic-release

      - store_test_results:
          path: reports/junit
      - store_artifacts:
          path: reports/junit
