@startuml
class Profile {
}
class User extends HaveMembers {
    +profile: Profile
}
class Member {
    +user: User
    +group: Group
    +profile: Profile
    +destroy(): void
    +{static} build(user: User, group: Group, profile?: Profile): Member
}
abstract class Identity {
    +id: string
}
abstract class HaveMembers extends Identity {
    -members: Set<Member>
    +add(member: Member): void
    +delete(member: Member): void
    +destroy(): void
    +size: number
    +has(member: Member): boolean
}
class Group extends HaveMembers {
    +owner: User
    +profile: Profile
}
class Index {
    +users: Set<User>
    +groups: Set<Group>
    -items: Map<string, Identity>
    +add(identity: Identity): Index
    +delete(identity: Identity): Index
    +get(id: string): Identity
}

Index o-- User
Index o-- Group
Member o-- Group
Member o-- User
HaveMembers *-- "many" Member
Profile o---l User
Profile o---l Group
Profile o-- Member
@enduml
